// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID        int64          `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:主键id" json:"id,string"`
	UserID    int64          `gorm:"column:user_id;type:int;not null;comment:谁发的消息,关联到user表id" json:"userId"`
	Category  int64          `gorm:"column:category;type:tinyint;not null;comment:消息类型,10表示私聊,11表示群聊,,0是单聊" json:"category"`
	TargetID  int64          `gorm:"column:target_id;type:int;not null;comment:如果是好友就关联到user表的id,如果是群聊就关联到community表id" json:"targetId"`
	Media     int64          `gorm:"column:media;type:tinyint;not null;comment:消息按照什么样式展示" json:"media"`
	Content   string         `gorm:"column:content;type:varchar(255);comment:消息内容体" json:"content"`
	Pic       string         `gorm:"column:pic;type:varchar(200);comment:图片预览地址" json:"pic"`
	URL       string         `gorm:"column:url;type:varchar(255);comment:服务的url" json:"url"`
	Remark    string         `gorm:"column:remark;type:varchar(100);comment:备注" json:"remark"`
	CreatedAt LocalTime      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt LocalTime      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp(6);comment:软删除时间" json:"-"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
