// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameOrder = "order"

// Order mapped from table <order>
type Order struct {
	ID                int64          `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:主键id" json:"id,string"`
	IsDel             int64          `gorm:"column:is_del;type:tinyint;not null;comment:是否删除,1表示删除,0表示正常" json:"isDel"`
	CreatedAt         LocalTime      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt         LocalTime      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
	OrderSn           string         `gorm:"column:order_sn;type:varchar(30);not null" json:"orderSn"`
	TradeNo           string         `gorm:"column:trade_no;type:varchar(100);comment:支付交易号(微信支付的交易号)" json:"tradeNo"`
	PayMethod         int64          `gorm:"column:pay_method;type:tinyint;not null;comment:支付方式0是微信,1是支付宝" json:"payMethod"`
	UserID            int64          `gorm:"column:user_id;type:int;not null;comment:交易的用户ID(小程序)" json:"userId"`
	ActivityID        int64          `gorm:"column:activity_id;type:int;not null;comment:订单关联活动的ID" json:"activityId"`
	ActivityEndTime   LocalTime      `gorm:"column:activity_end_time;type:timestamp;comment:活动结束时间" json:"activityEndTime"`
	PaidAmount        Decimal        `gorm:"column:paid_amount;type:decimal(13,2);not null;default:0.00;comment:支付金额(总金额)" json:"paidAmount"`
	StartPaidAt       LocalTime      `gorm:"column:start_paid_at;type:timestamp;comment:开始支付时间" json:"startPaidAt"`
	EndPaidAt         LocalTime      `gorm:"column:end_paid_at;type:timestamp;comment:支付成功时间" json:"endPaidAt"`
	Status            int64          `gorm:"column:status;type:tinyint;comment:支付状态,0表示未支付,1表示已支付,2表示支付失败,3表示取消订单,4表示退款,5表示核销,6表示在支付等待支付回调" json:"status"`
	Remark            string         `gorm:"column:remark;type:varchar(255);comment:备注信息" json:"remark"`
	CancelOrderReason string         `gorm:"column:cancel_order_reason;type:varchar(100);comment:取消订单原因" json:"cancelOrderReason"`
	SponsorID         int64          `gorm:"column:sponsor_id;type:int;not null;comment:订单关联主办方ID" json:"sponsorId"`
	ActivityTypeID    int64          `gorm:"column:activity_type_id;type:int;not null;comment:活动类型id" json:"activityTypeId"`
	TicketTotal       int64          `gorm:"column:ticket_total;type:int;comment:该订单下票数量" json:"ticketTotal"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp(6);comment:软删除时间" json:"-"`
	ActivityStartTime LocalTime      `gorm:"column:activity_start_time;type:timestamp;comment:活动开始时间" json:"activityStartTime"`
	RefundStatus      int64          `gorm:"column:refund_status;type:int;comment:退款状态" json:"refundStatus"`
	RefundTicketTotal int64          `gorm:"column:refund_ticket_total;type:int;comment:退票数量" json:"refundTicketTotal"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
