// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id,string"`
	Username  string         `gorm:"column:username;type:varchar(32);comment:用户名" json:"username"`
	Age       int64          `gorm:"column:age;type:int unsigned;not null;comment:年龄" json:"age"`
	Password  string         `gorm:"column:password;type:varchar(128);comment:密码" json:"password"`
	CreatedAt LocalTime      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt LocalTime      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:软删除时间" json:"-"`
	Phone     string         `gorm:"column:phone;type:varchar(11);not null;comment:手机号码" json:"phone"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
