// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameUserToken = "user_token"

// UserToken mapped from table <user_token>
type UserToken struct {
	ID         int64          `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:主键id" json:"id,string"`
	UserID     int64          `gorm:"column:user_id;type:int;not null;comment:关联到用户表id" json:"userId"`
	Token      string         `gorm:"column:token;type:varchar(100);not null;comment:token" json:"token"`
	ExpireTime LocalTime      `gorm:"column:expire_time;type:timestamp(6);comment:失效时间" json:"expireTime"`
	CreatedAt  LocalTime      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt  LocalTime      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp(6);comment:软删除时间" json:"-"`
}

// TableName UserToken's table name
func (*UserToken) TableName() string {
	return TableNameUserToken
}
