// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q         = new(Query)
	Message   *message
	Order     *order
	User      *user
	UserToken *userToken
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Message = &Q.Message
	Order = &Q.Order
	User = &Q.User
	UserToken = &Q.UserToken
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:        db,
		Message:   newMessage(db, opts...),
		Order:     newOrder(db, opts...),
		User:      newUser(db, opts...),
		UserToken: newUserToken(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Message   message
	Order     order
	User      user
	UserToken userToken
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Message:   q.Message.clone(db),
		Order:     q.Order.clone(db),
		User:      q.User.clone(db),
		UserToken: q.UserToken.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Message:   q.Message.replaceDB(db),
		Order:     q.Order.replaceDB(db),
		User:      q.User.replaceDB(db),
		UserToken: q.UserToken.replaceDB(db),
	}
}

type queryCtx struct {
	Message   IMessageDo
	Order     IOrderDo
	User      IUserDo
	UserToken IUserTokenDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Message:   q.Message.WithContext(ctx),
		Order:     q.Order.WithContext(ctx),
		User:      q.User.WithContext(ctx),
		UserToken: q.UserToken.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
